spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/easybuy?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: taotaotao
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, file:C:\Users\Ekko\Desktop\易买网-EasyBuy\upload
server:
  port: 80
mybatis:
  mapper-locations: classpath:mapper/*.xml
file:
  upload:
    path: C:\Users\Ekko\Desktop\易买网-EasyBuy\upload